version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./src/:/go/src/
    ports:
      - 7050:7050
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine3.14
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_todo
    volumes:
      - go-todo-ca-postgres-data:/var/lib/postgresql/data
    ports:
      - 7777:7777
volumes:
  go-todo-ca-postgres-data: